FROM node:alpine3.16
WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .
ARG APP_PORT
ARG USE_CACHE
ARG DATA_DB_URL
ARG CACHE_DB_URL
ARG STORE_LOGS
ENV APP_PORT=${APP_PORT}
ENV USE_CACHE=${USE_CACHE}
ENV DATA_DB_URL=${DATA_DB_URL}
ENV CACHE_DB_URL=${CACHE_DB_URL}
ENV STORE_LOGS=${STORE_LOGS}
CMD npm run start
EXPOSE 3000