FROM node:alpine
WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .
ARG APP_PORT
ARG USE_CACHE
ARG DATA_DB_HOST
ARG DATA_DB_PORT
ARG CACHE_DB_HOST
ARG CACHE_DB_PORT
ARG CORE_HOST
ARG CORE_PORT
ARG STORE_LOGS
ENV APP_PORT=${APP_PORT}
ENV USE_CACHE=${USE_CACHE}
ENV DATA_DB_HOST=${DATA_DB_HOST}
ENV DATA_DB_PORT=${DATA_DB_PORT}
ENV CACHE_DB_HOST=${CACHE_DB_HOST}
ENV CACHE_DB_PORT=${CACHE_DB_PORT}
ENV CORE_HOST=${CORE_HOST}
ENV CORE_PORT=${CORE_PORT}
ENV STORE_LOGS=${STORE_LOGS}
CMD npm run start
EXPOSE 3000