/**
 * The different types of resources that can be interacted with.
 *
 * @public
 */
export enum ResourceType {
	// LIST
	LIST_DETAILS = 'LIST_DETAILS',
	LIST_MEMBER_ADD = 'LIST_MEMBER_ADD',
	LIST_MEMBER_REMOVE = 'LIST_MEMBER_REMOVE',
	LIST_MEMBERS = 'LIST_MEMBERS',
	LIST_TWEETS = 'LIST_TWEETS',

	// MEDIA
	MEDIA_UPLOAD_APPEND = 'MEDIA_UPLOAD_APPEND',
	MEDIA_UPLOAD_FINALIZE = 'MEDIA_UPLOAD_FINALIZE',
	MEDIA_UPLOAD_INITIALIZE = 'MEDIA_UPLOAD_INITIALIZE',

	// DM
	DM_CONVERSATION = 'DM_CONVERSATION',
	DM_INBOX_INITIAL_STATE = 'DM_INBOX_INITIAL_STATE',
	DM_INBOX_TIMELINE = 'DM_INBOX_TIMELINE',
	DM_DELETE_CONVERSATION = 'DM_DELETE_CONVERSATION',

	// SPACE
	SPACE_DETAILS = 'SPACE_DETAILS',

	// TWEET
	TWEET_BOOKMARK = 'TWEET_BOOKMARK',
	TWEET_DETAILS = 'TWEET_DETAILS',
	TWEET_DETAILS_ALT = 'TWEET_DETAILS_ALT',
	TWEET_DETAILS_BULK = 'TWEET_DETAILS_BULK',
	TWEET_LIKE = 'TWEET_LIKE',
	TWEET_LIKERS = 'TWEET_LIKERS',
	TWEET_POST = 'TWEET_POST',
	TWEET_POST_NOTE = 'TWEET_POST_NOTE',
	TWEET_REPLIES = 'TWEET_REPLIES',
	TWEET_RETWEET = 'TWEET_RETWEET',
	TWEET_RETWEETERS = 'TWEET_RETWEETERS',
	TWEET_SCHEDULE = 'TWEET_SCHEDULE',
	TWEET_SEARCH = 'TWEET_SEARCH',
	TWEET_UNBOOKMARK = 'TWEET_UNBOOKMARK',
	TWEET_UNLIKE = 'TWEET_UNLIKE',
	TWEET_UNPOST = 'TWEET_UNPOST',
	TWEET_UNRETWEET = 'TWEET_UNRETWEET',
	TWEET_UNSCHEDULE = 'TWEET_UNSCHEDULE',

	// USER
	USER_AFFILIATES = 'USER_AFFILIATES',
	USER_ANALYTICS = 'USER_ANALYTICS',
	USER_BOOKMARKS = 'USER_BOOKMARKS',
	USER_BOOKMARK_FOLDERS = 'USER_BOOKMARK_FOLDERS',
	USER_BOOKMARK_FOLDER_TWEETS = 'USER_BOOKMARK_FOLDER_TWEETS',
	USER_ABOUT_BY_USERNAME = 'USER_ABOUT_BY_USERNAME',
	USER_DETAILS_BY_USERNAME = 'USER_DETAILS_BY_USERNAME',
	USER_DETAILS_BY_ID = 'USER_DETAILS_BY_ID',
	USER_DETAILS_BY_IDS_BULK = 'USER_DETAILS_BY_IDS_BULK',
	USER_FEED_FOLLOWED = 'USER_FEED_FOLLOWED',
	USER_FEED_RECOMMENDED = 'USER_FEED_RECOMMENDED',
	USER_FOLLOW = 'USER_FOLLOW',
	USER_FOLLOWING = 'USER_FOLLOWING',
	USER_FOLLOWERS = 'USER_FOLLOWERS',
	USER_HIGHLIGHTS = 'USER_HIGHLIGHTS',
	USER_LIKES = 'USER_LIKES',
	USER_LISTS = 'USER_LISTS',
	USER_MEDIA = 'USER_MEDIA',
	USER_NOTIFICATIONS = 'USER_NOTIFICATIONS',
	USER_REMOVE_FOLLOWER = 'USER_REMOVE_FOLLOWER',
	USER_SEARCH = 'USER_SEARCH',
	USER_SUBSCRIPTIONS = 'USER_SUBSCRIPTIONS',
	USER_TIMELINE = 'USER_TIMELINE',
	USER_TIMELINE_AND_REPLIES = 'USER_TIMELINE_AND_REPLIES',
	USER_UNFOLLOW = 'USER_UNFOLLOW',
	USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE',
	USER_PROFILE_IMAGE_UPDATE = 'USER_PROFILE_IMAGE_UPDATE',
	USER_PROFILE_BANNER_UPDATE = 'USER_PROFILE_BANNER_UPDATE',
	USER_USERNAME_CHANGE = 'USER_USERNAME_CHANGE',
	USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
}
